name: Python application

on: [push, pull_request]

# permissions:
#   checks: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: PYTHONPATH="${PWD}/src/layers/helper_layer/:${PWD}/src/layers/domain_layer/" python -m pytest --junit-xml=test-results.xml

    - name: Surface failing tests
      if: always()
      uses: pmeier/pytest-results-action@main
      with:
        path: '**/test-results.xml'
    
    # - name: Publish Unit Test Results
    #   uses: EnricoMi/publish-unit-test-result-action@v2.16.1
    #   with:
    #     files: '**/test-results.xml'
    # - name: Surface failing tests
    #   if: always()
    #   uses: pmeier/pytest-results-action@main
    #   with:
    #     path: '**/test-results.xml'
